apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.2.3
        profile:
            VendorType: partner
            version: v1.0
        chart-uri: https://github.com/mmulholla/development/blob/main/charts/partners/test-org/psql-service/0.1.9/psql-service-0.1.9.tgz?raw=true
        digests:
            chart: sha256:94cbcb63531bc4457e7b0314f781070bbfe4affbdca98f67acadc381bf0f0b4f
            package: 4e9592ea31c0509bec308905289491b7056b78bdde2ab71a85c72be0901759b8
        lastCertifiedTimestamp: "2021-11-04T10:25:46.372648-04:00"
        certifiedOpenShiftVersions: N/A
    chart:
        name: psql-service
        home: ""
        sources: []
        version: 0.1.9
        description: A Helm chart for a RedHat Certified PSQL
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 10.0.0
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: PSQL RedHat Demo Chart
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/dperaza4dustbit/helm-chart
        kubeversion: 1.20.0
        dependencies: []
        type: application
    chart-overrides: ""
results:
  - check: v1.0/has-readme
    type: Mandatory
    outcome: PASS
    reason: Chart has a README
  - check: v1.0/contains-test
    type: Mandatory
    outcome: PASS
    reason: Chart test files exist
  - check: v1.0/contains-values
    type: Mandatory
    outcome: PASS
    reason: Values file exist
  - check: v1.0/not-contains-crds
    type: Mandatory
    outcome: PASS
    reason: Chart does not contain CRDs
  - check: v1.0/is-helm-v3
    type: Mandatory
    outcome: PASS
    reason: API version is V2, used in Helm 3
  - check: v1.0/contains-values-schema
    type: Mandatory
    outcome: PASS
    reason: Values schema file exist
  - check: v1.0/has-kubeversion
    type: Mandatory
    outcome: PASS
    reason: Kubernetes version specified
  - check: v1.0/helm-lint
    type: Mandatory
    outcome: PASS
    reason: Helm lint successful
  - check: v1.0/not-contain-csi-objects
    type: Mandatory
    outcome: PASS
    reason: CSI objects do not exist
  - check: v1.0/images-are-certified
    type: Mandatory
    outcome: PASS
    reason: 'Image is Red Hat certified : registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest'
  - check: v1.0/chart-testing
    type: Mandatory
    outcome: FAIL
    reason: |-
        Error running process: executing helm with args "install psql-service-x18inv6z8q /Users/martinmulholland/Library/Caches/chart-verifier/https___github_com_mmulholla_development_blob_main_charts_partners_test_org_psql_service_0_1_9_psql_service_0_1_9_tgz_raw=true/psql-service --namespace default --wait --values /var/folders/19/zzj4wrnj1_g1wdtt_zn61_tm0000gn/T/chart-testing-1314855690/values.yaml": exit status 1
        ---
        Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://api.dev-svc-4.9-102014.devcluster.openshift.com:6443/version?timeout=32s": dial tcp: lookup api.dev-svc-4.9-102014.devcluster.openshift.com: no such host

